name: Python pipeline sanity

on:
  workflow_dispatch: {}

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Write data (pure shell, no Python)
        run: |
          mkdir -p data
          printf "ok,ts\ntrue,%s\n" "$(date -u +'%Y-%m-%dT%H:%M:%SZ')" > data/hello.csv
          ls -alh data
          head -n 5 data/hello.csv
