name: Python pipeline sanity

on:
  workflow_dispatch: {}

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Write data with Python (no pandas)
        run: |
          mkdir -p data
          python - <<'PY'
import csv, os, datetime as dt
os.makedirs("data", exist_ok=True)
with open("data/hello.csv", "w", newline="", encoding="utf-8") as f:
    w = csv.writer(f)
    w.writerow(["ok","ts"])
    w.writerow([True, dt.datetime.utcnow().isoformat()])
print("wrote data/hello.csv")
PY
          ls -alh data
          head -n 5 data/hello.csv
