name: Weekly scrape & update (shell)

on:
  workflow_dispatch: {}
  schedule:
    - cron: "0 6 * * 0"  # Sunday 15:00 KST

permissions:
  contents: write
  pull-requests: write

jobs:
  dry-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Make data file
        run: |
          mkdir -p data
          echo "sanity $(date -u +'%Y-%m-%dT%H:%M:%SZ')" > data/hello.txt
          ls -alh data
          head -n 1 data/hello.txt
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
          commit-message: "chore: sanity write under /data [skip ci]"
          title: "chore: sanity write under /data"
          body: "Automation sanity: create data/hello.txt"
          branch: automation/data-update
          delete-branch: true
